on:
  push:
    branches:
      - main

jobs:
  build:
    name: compose
    runs-on: [self-hosted]
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v3
      - name: ðŸ”¨ dependecies
        run: |
          npm install
      - name: ðŸ”¨ Build Project
        run: |
          npm run build
      - name: Docker Build image
        env:
          VITE_APP_BACKEND_URL: ${{ vars.VITE_APP_BACKEND_URL }}
        run: |
          echo "Build Started..."
          docker build --pull --rm -f "Dockerfile" -t kommunalka-vue:latest "."
      - name: Docker Compose
        env:
          VITE_APP_BACKEND_URL: ${{ vars.VITE_APP_BACKEND_URL }}
        run: |
          echo "Compose Started..."
          docker-compose up -d
